use_frameworks!

target 'curl_Example' do
  pod 'curl', :path => '../../'

  target 'curl_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
